[package]
name = "clipanion"
version = "0.6.1"
edition = "2021"
license = "MIT"
description = "A simple but powerful CLI framework"

[dependencies]
anyhow = { version = "1.0.86", optional = true }
clipanion-core = { path = "../clipanion-core", version = "0.6.0" }
clipanion-derive = { path = "../clipanion-derive", version = "0.6.0" }
colored = "2.1.0"
num-traits = "0.2.19"

[features]
anyhow = ["dep:anyhow"]
