[package]
name = "clipanion"
version = "0.8.1"
edition = "2021"
license = "MIT"
description = "A simple but powerful CLI framework"

[dependencies]
anyhow = { version = "1.0.86", optional = true }
clipanion-core = { path = "../clipanion-core", version = "0.8.1" }
clipanion-derive = { path = "../clipanion-derive", version = "0.8.1" }
colored = "2.1.0"
num-traits = "0.2.19"
serde_json = { version = "1.0.145", optional = true }

[features]
default = []
anyhow = ["dep:anyhow"]
serde = ["clipanion-core/serde", "dep:serde_json"]
tokens = ["clipanion-core/tokens", "serde"]
