[package]
name = "clipanion"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple but powerful CLI framework"

[dependencies]
partially = { version = "0.2.1", features = ["derive"] }
