[package]
name = "clipanion-demo"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple but powerful CLI framework"

[dependencies]
clipanion = { path = "../clipanion" }
thiserror = "1.0.63"
