[package]
name = "clipanion-demo"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A simple but powerful CLI framework"

[dependencies]
anyhow = "1.0.86"
clipanion = { path = "../clipanion", features = ["anyhow"] }
thiserror = "1.0.63"
